version: '3.9'
services:
   api:
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    depends_on:
      - database
    # We mount the working dir into the container, handy for development
    # This is what makes the hot reloading work inside of a Docker container
    volumes:
      - .:/app/
   database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5430:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
   panel:
    image: adminer:latest
    ports:
      - 8080:8080
volumes:
  pg-data:
  